<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>n. Ikon Cart</name>
   <tag></tag>
   <elementGuidId>9a4d55be-ae9a-469c-aad7-a9d4bae4cab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarNav']/ul[2]/li/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-cart-dash-fill.icon.me-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dafe1213-a54c-4425-b1fa-889206df6ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-cart-dash-fill icon me-2</value>
      <webElementGuid>862bd836-9231-4b18-86a1-bffb36b2d9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarNav&quot;)/ul[@class=&quot;navbar-nav ms-auto mb-2 mb-lg-0 d-flex flex-row align-items-center pt-3&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;d-flex flex-row align-items-center me-2&quot;]/i[@class=&quot;bi bi-cart-dash-fill icon me-2&quot;]</value>
      <webElementGuid>3240bac1-cedd-4e65-8ed1-32d40415839d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarNav']/ul[2]/li/a/i</value>
      <webElementGuid>209ce5d1-f515-4498-a2a1-81ce5ae821fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>7c0bd01c-b9e6-42df-9233-7cce733b882d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
